;;;; src/util/package.lisp -- the packages, and the layering they encode.
;;;;
;;;; CRT.UTIL, CRT.SETTINGS, CRT.VT, CRT.PTY and CRT.TERMINAL must not mention
;;;; Objective-C or anything SBCL-only.  That is not tidiness: it is what lets
;;;; the ECL leg of CI load and test them, and what keeps the parts of this
;;;; program that can be reasoned about without a GPU separable from the parts
;;;; that cannot.

(defpackage #:cathode-ray-tube.util
  (:use #:cl)
  (:nicknames #:crt.util)
  (:export
   ;; math -- the arithmetic cool-retro-term's utils.js and fontmanager.cpp do,
   ;; reproduced exactly, quirks included.
   #:clamp #:lint #:smoothstep #:qround
   ;; color
   #:rgba #:rgba-r #:rgba-g #:rgba-b #:rgba-a #:make-rgba
   #:str-to-color #:color-to-str #:mix-color #:sum-color #:scale-color
   #:rgb2grey
   ;; resource
   #:resource #:*resource-directory*))

(defpackage #:cathode-ray-tube.metal
  (:use #:cl)
  (:nicknames #:crt.metal)
  (:local-nicknames (#:util #:cathode-ray-tube.util))
  (:export
   ;; device
   #:with-metal #:ensure-frameworks #:ensure-metal #:metal-available-p #:default-device #:device-name
   #:command-queue #:command-buffer #:reset-device #:null-object-p
   #:apple-gpu-p #:texture-storage-mode
   #:*device* #:*queue*
   ;; resources
   #:texture #:texture-p #:texture-handle #:texture-width #:texture-height
   #:texture-pixel-format #:make-texture #:release-texture
   #:texture-storage #:texture-bytes #:texture-pixel #:bytes-per-pixel
   #:synchronize-texture
   #:make-sampler #:with-mtl-region
   #:buffer #:buffer-p #:buffer-handle #:buffer-contents #:buffer-length
   #:make-buffer #:release-buffer #:bind-vertex-buffer
   ;; library and pipelines
   #:default-library #:compile-library #:make-function
   #:pipeline #:clear-pipeline-cache
   ;; passes
   #:with-render-pass #:render-pass-descriptor #:use-pipeline
   #:draw-quad #:draw-instances
   #:bind-fragment-texture #:bind-fragment-sampler
   #:bind-fragment-bytes #:bind-vertex-bytes
   #:with-clear-color #:with-viewport
   #:define-uniform-block #:with-uniforms #:uref #:bind-uniforms
   #:uniform-block-size #:uniform-block-layout #:uniform-offset
   #:compute-uniform-layout
   ;; constants, generated by tools/metal-constants.sh
   #:*metal-constants*
   #:+pixel-format-r8unorm+ #:+pixel-format-rgba8unorm+
   #:+pixel-format-bgra8unorm+ #:+pixel-format-rgba16float+
   #:+texture-type-2d+
   #:+usage-shader-read+ #:+usage-shader-write+ #:+usage-render-target+
   #:+storage-mode-shared+ #:+storage-mode-managed+ #:+storage-mode-private+
   #:+resource-storage-mode-shift+ #:+gpu-family-apple1+
   #:+load-action-dont-care+ #:+load-action-load+ #:+load-action-clear+
   #:+store-action-dont-care+ #:+store-action-store+
   #:+primitive-triangle+ #:+primitive-triangle-strip+
   #:+data-type-float+ #:+data-type-int+ #:+data-type-bool+
   #:+filter-nearest+ #:+filter-linear+
   #:+address-clamp-to-edge+ #:+address-repeat+
   #:+blend-factor-one+ #:+blend-factor-zero+
   #:+blend-factor-src-alpha+ #:+blend-factor-one-minus-src-alpha+
   #:+blend-operation-add+))

(defpackage #:cathode-ray-tube.settings
  (:use #:cl)
  (:nicknames #:crt.settings)
  (:local-nicknames (#:util #:cathode-ray-tube.util))
  (:export
   #:profile #:profile-p #:make-profile #:copy-profile
   #:profile-name #:find-profile #:+profiles+ #:profile-names
   ;; the 27 keys
   #:profile-ambient-light #:profile-background-color #:profile-bloom
   #:profile-brightness #:profile-burn-in #:profile-chroma-color
   #:profile-contrast #:profile-flickering #:profile-font-color
   #:profile-font-name #:profile-font-source #:profile-font-width
   #:profile-line-spacing #:profile-glowing-line #:profile-horizontal-sync
   #:profile-jitter #:profile-rasterization #:profile-rgb-shift
   #:profile-saturation-color #:profile-screen-curvature #:profile-screen-radius
   #:profile-static-noise #:profile-window-opacity #:profile-margin
   #:profile-blinking-cursor #:profile-frame-size #:profile-frame-color
   #:profile-frame-shininess
   ;; derived
   #:saturated-color #:derived-font-color #:derived-background-color
   #:derived-frame-color #:frame-enabled-p #:frame-size #:frame-shininess
   #:screen-radius #:margin #:burn-in-fade-time #:horizontal-sync-strength
   #:rasterization-intensity #:normalized-window-scale
   #:+raster-none+ #:+raster-scanlines+ #:+raster-pixels+
   #:+raster-subpixels+ #:+raster-modern+
   #:+screen-curvature-size+ #:+min-burn-in-fade-time+ #:+max-burn-in-fade-time+
   #:+base-font-scaling+ #:contrast-mix
   ;; serialisation
   #:profile-to-alist #:profile-from-alist #:profile-to-json #:profile-from-json
   ;; the small JSON reader and writer, which exists because jzon does not
   ;; compile on ECL -- see src/settings/json.lisp
   #:read-json #:write-json #:json-error #:json-error-message
   ;; the settings store
   #:settings #:settings-p #:make-settings #:copy-settings #:*settings*
   #:settings-profile-name #:settings-effects #:settings-effects-frame-skip
   #:settings-window-scaling #:settings-bloom-quality #:settings-burn-in-quality
   #:settings-font-scaling #:settings-columns #:settings-rows
   #:settings-show-terminal-size #:settings-use-custom-command
   #:settings-custom-command #:settings-custom-profiles
   #:save-settings #:load-settings #:load-settings-into-place #:settings-file
   #:all-profiles #:find-any-profile #:builtin-profile-p
   #:save-custom-profile #:remove-custom-profile))

(defpackage #:cathode-ray-tube.vt
  (:use #:cl)
  (:nicknames #:crt.vt)
  (:local-nicknames (#:util #:cathode-ray-tube.util))
  (:export
   ;; the backend protocol -- everything above this package talks to these and
   ;; never to CFFI, so a different terminal core is a file rather than a rewrite
   #:vt #:make-vt #:vt-close #:vt-open-p
   #:vt-write #:vt-resize #:vt-reset
   #:vt-rows #:vt-cols #:vt-cell #:vt-row-cells #:vt-cursor
   #:vt-dirty-rows #:vt-dirty-p #:vt-clear-dirty #:vt-damage-all
   #:vt-text #:vt-scrollback-length #:vt-scrollback-line
   #:vt-title #:vt-bell-count #:vt-output-hook
   #:vt-mouse-reporting-p #:vt-alternate-screen-p
   #:vt-mouse-move #:vt-mouse-button #:vt-start-paste #:vt-end-paste
   ;; cells
   #:cell #:make-cell #:cell-p #:copy-cell
   #:cell-char #:cell-combining #:cell-width
   #:cell-fg #:cell-bg #:cell-attrs
   #:cell-blank-p
   #:+attr-bold+ #:+attr-underline+ #:+attr-italic+ #:+attr-blink+
   #:+attr-reverse+ #:+attr-conceal+ #:+attr-strike+
   #:attr-set-p #:cell-underline-style #:+attr-underline-shift+
   ;; colours
   #:vt-color #:vt-color-p #:vt-color-indexed-p #:vt-color-index
   #:vt-color-red #:vt-color-green #:vt-color-blue
   #:vt-color-default-fg-p #:vt-color-default-bg-p
   #:resolve-color #:+default-palette+))

(defpackage #:cathode-ray-tube.pty
  (:use #:cl)
  (:nicknames #:crt.pty)
  (:local-nicknames (#:util #:cathode-ray-tube.util))
  (:export
   #:pty #:pty-p #:pty-fd #:pty-pid #:pty-alive-p
   #:spawn-pty #:pty-close #:pty-read #:pty-write #:pty-reap
   #:set-winsize #:get-winsize
   #:default-shell #:login-shell-arguments #:shell-command #:child-environment))

(defpackage #:cathode-ray-tube.terminal
  (:use #:cl)
  (:nicknames #:crt.terminal)
  (:local-nicknames (#:util #:cathode-ray-tube.util)
                    (#:vt #:cathode-ray-tube.vt)
                    (#:pty #:cathode-ray-tube.pty))
  (:export
   #:terminal #:make-terminal #:terminal-close
   #:terminal-vt #:terminal-pty #:terminal-lock
   #:terminal-rows #:terminal-cols #:terminal-resize
   #:terminal-alive-p #:terminal-exit-status #:terminal-on-exit #:terminal-on-title
   #:terminal-send #:terminal-send-string #:terminal-paste
   #:terminal-mouse-reporting-p #:terminal-alternate-screen-p
   #:terminal-report-mouse #:terminal-scroll #:terminal-scroll-to-bottom
   #:terminal-scroll-offset #:terminal-scrollback-length
   #:with-terminal-locked #:terminal-take-dirty #:terminal-title
   #:terminal-snapshot #:snapshot #:snapshot-p #:make-snapshot
   #:snapshot-rows #:snapshot-cols #:snapshot-cells #:snapshot-dirty
   #:snapshot-cursor-row #:snapshot-cursor-col #:snapshot-cursor-visible
   #:snapshot-painted))

(defpackage #:cathode-ray-tube.text
  (:use #:cl)
  (:nicknames #:crt.text)
  (:local-nicknames (#:util #:cathode-ray-tube.util)
                    (#:metal #:cathode-ray-tube.metal)
                    (#:vt #:cathode-ray-tube.vt)
                    (#:term #:cathode-ray-tube.terminal))
  (:export
   ;; fonts
   #:font #:font-p #:font-handle #:font-pixel-size #:font-ascent #:font-descent
   #:font-cell-width #:font-cell-height #:font-advance
   #:load-font #:release-font #:bundled-font-path #:+bundled-fonts+
   #:font-pixel-size
   ;; the atlas
   #:atlas #:atlas-p #:make-atlas #:release-atlas #:atlas-texture
   #:atlas-width #:atlas-height #:atlas-glyph #:glyph
   #:glyph-u0 #:glyph-v0 #:glyph-u1 #:glyph-v1
   #:glyph-width #:glyph-height #:glyph-bearing-x #:glyph-bearing-y
   #:glyph-advance #:atlas-flush
   ;; the pass
   #:text-renderer #:make-text-renderer #:release-text-renderer
   #:text-renderer-atlas #:text-renderer-font #:text-renderer-target
   #:render-text #:text-grid-size #:grid-pixel-size #:resize-text-renderer
   #:text-renderer-scale #:text-renderer-cols #:text-renderer-rows
   #:text-renderer-cell-width #:text-renderer-cell-height
   #:text-renderer-font-width #:cell-advance
   #:text-renderer-line-spacing #:line-height #:text-renderer-virtual-size
   #:bundled-font-low-resolution-p #:load-bundled-font
   #:font-for-profile-name #:+profile-font-names+
   #:bundled-font-native-size))

(defpackage #:cathode-ray-tube.effects
  (:use #:cl)
  (:nicknames #:crt.effects)
  (:local-nicknames (#:util #:cathode-ray-tube.util)
                    (#:metal #:cathode-ray-tube.metal)
                    (#:settings #:cathode-ray-tube.settings))
  (:export
   #:graph #:graph-p #:make-graph #:release-graph #:resize-graph
   #:set-graph-quality
   #:render-effects #:graph-profile #:graph-quality
   #:graph-window-scaling #:graph-bloom-quality #:graph-burn-in-quality
   #:+k-raster-mode+ #:+k-burn-in+ #:+k-display-frame+ #:+k-chroma+
   #:+k-rgb-shift+ #:+k-bloom+ #:+k-curvature+ #:+k-frame-shininess+
   #:dynamic-pipeline-constants #:static-pipeline-constants))

(defpackage #:cathode-ray-tube.ui
  (:use #:cl)
  (:nicknames #:crt.ui)
  (:local-nicknames (#:util #:cathode-ray-tube.util))
  (:export
   #:ensure-appkit #:handling-errors #:run
   #:crt-view #:view-layer #:view-link #:view-frame-skip #:view-effect-time
   #:view-frames #:view-drawable-size #:view-draw-function
   #:attach-metal-layer #:start-display-link #:stop-display-link #:step-frame
   #:crt-window #:crt-window-p #:crt-window-handle #:crt-window-view
   #:make-crt-window #:show-crt-window #:close-crt-window #:*windows*
   #:make-menu-bar #:menu-item #:menu-separator #:submenu #:gradient-frame
   #:view-resized-p #:view-key-handler #:view-mouse-handlers #:event-key-string
   #:on-main-thread #:drain-main-thread-queue
   #:session #:session-p #:make-session #:end-session #:run-terminal
   #:session-window #:session-view #:session-terminal #:session-renderer
   #:session-font #:session-margin #:profile-font
   #:*sessions* #:*default-font* #:*default-profile*
   #:*default-columns* #:*default-rows* #:screen-backing-scale
   #:session-profile #:session-graph #:set-session-profile
   ;; geometry
   #:distort-point #:view-point-to-cell
   ;; selection and the clipboard
   #:selection #:make-selection #:selection-p #:selection-ordered
   #:selection-empty-p #:cell-selected-p #:selection-text #:session-selection
   #:session-dragging #:clear-selection #:copy-selection #:paste-clipboard
   #:clipboard-string #:set-clipboard-string #:word-bounds
   #:handle-mouse-down #:handle-mouse-up #:handle-mouse-dragged
   #:handle-double-click #:handle-scroll-wheel #:show-context-menu
   ;; zoom and scrolling
   #:zoom-in #:zoom-out #:zoom-reset #:set-font-scaling #:session-font-scaling
   #:scroll-viewport #:session-effects
   ;; menu actions
   #:menu-target #:key-session #:show-about-panel))

(defpackage #:cathode-ray-tube
  (:use #:cl)
  (:nicknames #:crt)
  (:local-nicknames (#:util #:cathode-ray-tube.util)
                    (#:metal #:cathode-ray-tube.metal)
                    (#:ui #:cathode-ray-tube.ui))
  (:export #:main #:parse-command-line #:tokenize-command-line #:version
           #:+usage+ #:apply-options))
