;;;; src/metal/constants.lisp -- Metal's enumerations, READ from the SDK.
;;;;
;;;; GENERATED by tools/metal-constants.sh.  Regenerate with `make constants';
;;;; `make check-metal-constants' asserts this file still agrees with the SDK on
;;;; the machine doing the building, and skips where Xcode is absent.
;;;;
;;;; Why generate at all, when Apple has never renumbered one of these?  Because
;;;; a typo in a hand-copied table does not raise an error.  Passing 71 instead
;;;; of 70 for a pixel format gets you a pipeline that builds, a texture that
;;;; allocates, and a black window -- and `objc' has no constant tables of its
;;;; own to check against, because it sends messages and a message does not know
;;;; what 70 means.  Reading them costs one shell script and removes the whole
;;;; class.

(in-package #:cathode-ray-tube.metal)

(defmacro define-metal-constants (&body pairs)
  "DEFCONSTANT each (NAME . VALUE) as +NAME+, and record the set for the test."
  `(progn
     ,@(loop for (name . value) in pairs
             collect `(defconstant ,(intern (format nil "+~A+" name))
                        ,value))
     (defparameter *metal-constants*
       ',pairs
       "The generated table, so tests/metal-tests.lisp can re-read the SDK and
compare without parsing this file.")))

(define-metal-constants
  (pixel-format-r8unorm . 10)
  (pixel-format-rgba8unorm . 70)
  (pixel-format-bgra8unorm . 80)
  (pixel-format-rgba16float . 115)
  (texture-type-2d . 2)
  (usage-shader-read . 1)
  (usage-shader-write . 2)
  (usage-render-target . 4)
  (storage-mode-shared . 0)
  (storage-mode-managed . 1)
  (storage-mode-private . 2)
  (load-action-dont-care . 0)
  (load-action-load . 1)
  (load-action-clear . 2)
  (store-action-dont-care . 0)
  (store-action-store . 1)
  (primitive-triangle . 3)
  (primitive-triangle-strip . 4)
  (data-type-float . 3)
  (data-type-int . 29)
  (data-type-bool . 53)
  (filter-nearest . 0)
  (filter-linear . 1)
  (address-clamp-to-edge . 0)
  (address-repeat . 2)
  (blend-factor-one . 1)
  (blend-factor-zero . 0)
  (blend-factor-src-alpha . 4)
  (blend-factor-one-minus-src-alpha . 5)
  (blend-operation-add . 0)
  )
