;;;; src/settings/builtin-profiles.lisp -- the fourteen, value for value.
;;;;
;;;; GENERATED by tools/extract-profiles.py from cool-retro-term's
;;;; app/qml/ApplicationSettings.qml, and not retyped.  Twenty-seven numbers
;;;; times fourteen profiles is nearly four hundred opportunities for a
;;;; transcription error that nobody would ever notice: a profile that is
;;;; slightly wrong looks like a profile.
;;;;
;;;; These are the numbers that define what this program is for, so they are
;;;; copied mechanically and checked mechanically -- tests/profile-tests.lisp
;;;; re-reads the QML and asserts this file still agrees with it.

(in-package #:cathode-ray-tube.settings)

(defparameter +profiles+
  (list
    (make-profile
     :name "Default Amber"
     :ambient-light 0.3d0
     :background-color "#000000"
     :bloom 0.6d0
     :brightness 0.5d0
     :burn-in 0.3d0
     :chroma-color 0.2d0
     :contrast 0.8d0
     :flickering 0.1d0
     :font-color "#ff8100"
     :font-name "TERMINESS_SCALED"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.2d0
     :horizontal-sync 0.1d0
     :jitter 0.2d0
     :rasterization 0
     :rgb-shift 0.0d0
     :saturation-color 0.2d0
     :screen-curvature 0.2d0
     :screen-radius 0.1d0
     :static-noise 0.1d0
     :window-opacity 1.0d0
     :margin 0.3d0
     :blinking-cursor nil
     :frame-size 0.1d0
     :frame-color "#cfcfcf"
     :frame-shininess 0.3d0)
    (make-profile
     :name "Monochrome Green"
     :ambient-light 0.3d0
     :background-color "#000000"
     :bloom 0.5d0
     :brightness 0.5d0
     :burn-in 0.3d0
     :chroma-color 0.0d0
     :contrast 0.8d0
     :flickering 0.1d0
     :font-color "#0ccc68"
     :font-name "DEPARTURE_MONO_SCALED"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.2d0
     :horizontal-sync 0.1d0
     :jitter 0.2d0
     :rasterization 0
     :rgb-shift 0.0d0
     :saturation-color 0.0d0
     :screen-curvature 0.3d0
     :screen-radius 0.2d0
     :static-noise 0.1d0
     :window-opacity 1.0d0
     :margin 0.3d0
     :blinking-cursor nil
     :frame-size 0.1d0
     :frame-color "#d4d4d4"
     :frame-shininess 0.1d0)
    (make-profile
     :name "Deep Blue"
     :ambient-light 0.0d0
     :background-color "#000000"
     :bloom 0.6d0
     :brightness 0.5d0
     :burn-in 0.3d0
     :chroma-color 1.0d0
     :contrast 0.8d0
     :flickering 0.1d0
     :font-color "#7fb4ff"
     :font-name "BIGBLUE_TERMINAL_SCALED"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.2d0
     :horizontal-sync 0.1d0
     :jitter 0.2d0
     :rasterization 0
     :rgb-shift 0.0d0
     :saturation-color 0.2d0
     :screen-curvature 0.4d0
     :screen-radius 0.1d0
     :static-noise 0.1d0
     :window-opacity 1.0d0
     :margin 0.3d0
     :blinking-cursor nil
     :frame-size 0.1d0
     :frame-color "#ffffff"
     :frame-shininess 0.9d0)
    (make-profile
     :name "Commodore 64"
     :ambient-light 0.4d0
     :background-color "#3b3b8f"
     :bloom 0.4d0
     :brightness 0.6d0
     :burn-in 0.1d0
     :chroma-color 0.0d0
     :contrast 0.7d0
     :flickering 0.1d0
     :font-color "#a9a7ff"
     :font-name "COMMODORE_64_SCALED"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.1d0
     :horizontal-sync 0.0d0
     :jitter 0.0d0
     :rasterization 1
     :rgb-shift 0.0d0
     :saturation-color 0.0d0
     :screen-curvature 0.5d0
     :screen-radius 0.1d0
     :static-noise 0.1d0
     :window-opacity 1.0d0
     :margin 0.3d0
     :blinking-cursor nil
     :frame-size 0.5d0
     :frame-color "#999999"
     :frame-shininess 0.0d0)
    (make-profile
     :name "Commodore PET"
     :ambient-light 0.0d0
     :background-color "#000000"
     :bloom 0.4d0
     :brightness 0.5d0
     :burn-in 0.4d0
     :chroma-color 0.0d0
     :contrast 0.8d0
     :flickering 0.2d0
     :font-color "#ffffff"
     :font-name "COMMODORE_PET_SCALED"
     :font-source 0
     :font-width 1.25d0
     :line-spacing 0.1d0
     :glowing-line 0.3d0
     :horizontal-sync 0.2d0
     :jitter 0.15d0
     :rasterization 1
     :rgb-shift 0.0d0
     :saturation-color 0.0d0
     :screen-curvature 0.7d0
     :screen-radius 0.3d0
     :static-noise 0.2d0
     :window-opacity 1.0d0
     :margin 0.2d0
     :blinking-cursor nil
     :frame-size 0.5d0
     :frame-color "#000000"
     :frame-shininess 0.6d0)
    (make-profile
     :name "Apple ]["
     :ambient-light 1.0d0
     :background-color "#001100"
     :bloom 0.3d0
     :brightness 0.5d0
     :burn-in 0.3d0
     :chroma-color 0.0d0
     :contrast 0.8d0
     :flickering 0.2d0
     :font-color "#4dff6b"
     :font-name "APPLE_II_SCALED"
     :font-source 0
     :font-width 1.25d0
     :line-spacing 0.1d0
     :glowing-line 0.3d0
     :horizontal-sync 0.2d0
     :jitter 0.2d0
     :rasterization 1
     :rgb-shift 0.0d0
     :saturation-color 0.0d0
     :screen-curvature 0.5d0
     :screen-radius 0.3d0
     :static-noise 0.2d0
     :window-opacity 1.0d0
     :margin 0.0d0
     :blinking-cursor nil
     :frame-size 0.2d0
     :frame-color "#ffffff"
     :frame-shininess 0.8d0)
    (make-profile
     :name "Atari 400"
     :ambient-light 0.1d0
     :background-color "#0f1f5a"
     :bloom 0.1d0
     :brightness 0.6d0
     :burn-in 0.2d0
     :chroma-color 0.0d0
     :contrast 0.9d0
     :flickering 0.1d0
     :font-color "#8ed6ff"
     :font-name "ATARI_400_SCALED"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.1d0
     :horizontal-sync 0.0d0
     :jitter 0.0d0
     :rasterization 1
     :rgb-shift 0.0d0
     :saturation-color 0.0d0
     :screen-curvature 0.4d0
     :screen-radius 0.2d0
     :static-noise 0.1d0
     :window-opacity 1.0d0
     :margin 0.2d0
     :blinking-cursor nil
     :frame-size 0.4d0
     :frame-color "#cccccc"
     :frame-shininess 0.3d0)
    (make-profile
     :name "IBM VGA 8x16"
     :ambient-light 0.2d0
     :background-color "#000000"
     :bloom 0.2d0
     :brightness 0.6d0
     :burn-in 0.1d0
     :chroma-color 0.5d0
     :contrast 1.0d0
     :flickering 0.1d0
     :font-color "#c0c0c0"
     :font-name "IBM_VGA_8x16"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.1d0
     :horizontal-sync 0.0d0
     :jitter 0.0d0
     :rasterization 1
     :rgb-shift 0.1d0
     :saturation-color 0.0d0
     :screen-curvature 0.3d0
     :screen-radius 0.1d0
     :static-noise 0.0d0
     :window-opacity 1.0d0
     :margin 0.2d0
     :blinking-cursor nil
     :frame-size 0.1d0
     :frame-color "#ffffff"
     :frame-shininess 0.3d0)
    (make-profile
     :name "IBM 3278 Reborn"
     :ambient-light 0.2d0
     :background-color "#000000"
     :bloom 0.2d0
     :brightness 0.5d0
     :burn-in 0.5d0
     :chroma-color 0.0d0
     :contrast 0.8d0
     :flickering 0.0d0
     :font-color "#3cff7a"
     :font-name "IBM_3278"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.0d0
     :horizontal-sync 0.0d0
     :jitter 0.0d0
     :rasterization 4
     :rgb-shift 0.0d0
     :saturation-color 0.0d0
     :screen-curvature 0.0d0
     :screen-radius 0.0d0
     :static-noise 0.0d0
     :window-opacity 1.0d0
     :margin 0.1d0
     :blinking-cursor nil
     :frame-size 0.0d0
     :frame-color "#ffffff"
     :frame-shininess 0.2d0)
    (make-profile
     :name "Neon Cyan"
     :ambient-light 0.1d0
     :background-color "#001018"
     :bloom 0.6d0
     :brightness 0.6d0
     :burn-in 0.1d0
     :chroma-color 1.0d0
     :contrast 0.9d0
     :flickering 0.1d0
     :font-color "#52f7ff"
     :font-name "IOSEVKA"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.2d0
     :horizontal-sync 0.0d0
     :jitter 0.1d0
     :rasterization 4
     :rgb-shift 0.0d0
     :saturation-color 0.6d0
     :screen-curvature 0.0d0
     :screen-radius 0.0d0
     :static-noise 0.1d0
     :window-opacity 0.8d0
     :margin 0.1d0
     :blinking-cursor nil
     :frame-size 0.0d0
     :frame-color "#c3c3c3"
     :frame-shininess 0.2d0)
    (make-profile
     :name "Ghost Terminal"
     :ambient-light 0.3d0
     :background-color "#0b1014"
     :bloom 0.3d0
     :brightness 0.6d0
     :burn-in 0.2d0
     :chroma-color 0.0d0
     :contrast 0.5d0
     :flickering 0.0d0
     :font-color "#a6b3c0"
     :font-name "JETBRAINS_MONO"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.1d0
     :horizontal-sync 0.0d0
     :jitter 0.0d0
     :rasterization 4
     :rgb-shift 0.0d0
     :saturation-color 0.0d0
     :screen-curvature 0.0d0
     :screen-radius 0.0d0
     :static-noise 0.1d0
     :window-opacity 0.7d0
     :margin 0.1d0
     :blinking-cursor nil
     :frame-size 0.0d0
     :frame-color "#a7a7a7"
     :frame-shininess 0.2d0)
    (make-profile
     :name "Plasma"
     :ambient-light 0.1d0
     :background-color "#070014"
     :bloom 0.7d0
     :brightness 0.6d0
     :burn-in 0.1d0
     :chroma-color 1.0d0
     :contrast 0.8d0
     :flickering 0.1d0
     :font-color "#ff9bd6"
     :font-name "FIRA_CODE"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.2d0
     :horizontal-sync 0.0d0
     :jitter 0.1d0
     :rasterization 4
     :rgb-shift 0.1d0
     :saturation-color 0.8d0
     :screen-curvature 0.0d0
     :screen-radius 0.0d0
     :static-noise 0.1d0
     :window-opacity 1.0d0
     :margin 0.1d0
     :blinking-cursor nil
     :frame-size 0.0d0
     :frame-color "#d0d0d0"
     :frame-shininess 0.2d0)
    (make-profile
     :name "Boring"
     :ambient-light 0.1d0
     :background-color "#000000"
     :bloom 0.5d0
     :brightness 0.5d0
     :burn-in 0.05d0
     :chroma-color 1.0d0
     :contrast 0.8d0
     :flickering 0.0d0
     :font-color "#ffffff"
     :font-name "JETBRAINS_MONO"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.1d0
     :horizontal-sync 0.0d0
     :jitter 0.0d0
     :rasterization 4
     :rgb-shift 0.0d0
     :saturation-color 0.0d0
     :screen-curvature 0.0d0
     :screen-radius 0.0d0
     :static-noise 0.0d0
     :window-opacity 1.0d0
     :margin 0.0d0
     :blinking-cursor nil
     :frame-size 0.0d0
     :frame-color "#c0c0c0"
     :frame-shininess 0.2d0)
    (make-profile
     :name "E-Ink"
     :ambient-light 0.6d0
     :background-color "#f2f2ec"
     :bloom 0.0d0
     :brightness 1.0d0
     :burn-in 0.6d0
     :chroma-color 0.0d0
     :contrast 0.5d0
     :flickering 0.0d0
     :font-color "#101010"
     :font-name "HACK"
     :font-source 0
     :font-width 1.0d0
     :line-spacing 0.1d0
     :glowing-line 0.0d0
     :horizontal-sync 0.0d0
     :jitter 0.0d0
     :rasterization 4
     :rgb-shift 0.0d0
     :saturation-color 0.0d0
     :screen-curvature 0.0d0
     :screen-radius 0.0d0
     :static-noise 0.0d0
     :window-opacity 1.0d0
     :margin 0.1d0
     :blinking-cursor nil
     :frame-size 0.0d0
     :frame-color "#cdcdcd"
     :frame-shininess 0.2d0))
  "cool-retro-term's built-in profiles, in its own menu order.")

(defun profile-names ()
  (mapcar #'profile-name +profiles+))

(defun find-profile (name)
  "The built-in profile called NAME, or NIL."
  (find name +profiles+ :key #'profile-name :test #'string-equal))
