#!/usr/bin/env python3
"""Extract cool-retro-term's built-in profiles into Lisp.

Twenty-seven numbers times fourteen profiles is nearly four hundred chances to
mistype something that nobody would ever notice, because a profile that is
slightly wrong still looks like a profile.  So they are copied mechanically.

    tools/extract-profiles.py ~/Projects/cool-retro-term > src/settings/builtin-profiles.lisp

tests/profile-tests.lisp re-runs this and asserts the checked-in file still
agrees, skipping where the cool-retro-term checkout is not present.
"""
import json, os, re, sys

KEYS = ["ambientLight", "backgroundColor", "bloom", "brightness", "burnIn",
        "chromaColor", "contrast", "flickering", "fontColor", "fontName",
        "fontSource", "fontWidth", "lineSpacing", "glowingLine",
        "horizontalSync", "jitter", "rasterization", "rgbShift",
        "saturationColor", "screenCurvature", "screenRadius", "staticNoise",
        "windowOpacity", "margin", "blinkingCursor", "frameSize", "frameColor",
        "frameShininess"]

def kebab(name):
    return re.sub(r'(?<!^)(?=[A-Z])', '-', name).lower()

def literal(key, value):
    if isinstance(value, bool):
        return "t" if value else "nil"
    if isinstance(value, str):
        return '"%s"' % value
    if key in ("rasterization", "fontSource"):
        return str(int(value))
    text = repr(float(value))
    return text + "d0" if "d" not in text and "e" not in text else text

def main(root):
    qml = os.path.join(root, "app/qml/ApplicationSettings.qml")
    source = open(qml).read()
    blocks = re.findall(r'text:\s*"([^"]+)"\s*\n\s*obj_string:\s*\'(\{.*?\})\'',
                        source, re.S)
    if len(blocks) != 14:
        sys.exit("expected 14 profiles in %s, found %d" % (qml, len(blocks)))
    out = []
    for name, obj in blocks:
        parsed = json.loads(obj)
        missing = [k for k in KEYS if k not in parsed]
        if missing:
            sys.exit("%s is missing %s" % (name, ", ".join(missing)))
        fields = "\n     ".join(":%s %s" % (kebab(k), literal(k, parsed[k]))
                                for k in KEYS)
        out.append('    (make-profile\n     :name "%s"\n     %s)' % (name, fields))

    print(""";;;; src/settings/builtin-profiles.lisp -- the fourteen, value for value.
;;;;
;;;; GENERATED by tools/extract-profiles.py from cool-retro-term's
;;;; app/qml/ApplicationSettings.qml, and not retyped.  Twenty-seven numbers
;;;; times fourteen profiles is nearly four hundred opportunities for a
;;;; transcription error that nobody would ever notice: a profile that is
;;;; slightly wrong looks like a profile.
;;;;
;;;; These are the numbers that define what this program is for, so they are
;;;; copied mechanically and checked mechanically -- tests/profile-tests.lisp
;;;; re-reads the QML and asserts this file still agrees with it.

(in-package #:cathode-ray-tube.settings)

(defparameter +profiles+
  (list""")
    print("\n".join(out) + ")")
    print('  "cool-retro-term\'s built-in profiles, in its own menu order.")')
    print("""
(defun profile-names ()
  (mapcar #'profile-name +profiles+))

(defun find-profile (name)
  "The built-in profile called NAME, or NIL."
  (find name +profiles+ :key #'profile-name :test #'string-equal))""")

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1
         else os.path.expanduser("~/Projects/cool-retro-term"))
